version: '3.1'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nathee2024
      MYSQL_DATABASE: MyPOS
      MYSQL_USER: nathee
      MYSQL_PASSWORD: nathee2024
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
